### PR TITLE
Prototype for MaybeUninit formulation of arrayvec

### PR DESCRIPTION
**Pull request by bluss**
- Testing ideas for arrayvec 1.0
- Looking at what is well defined and what's not
- Not adequate yet:
  - How to handle uninitialization?
  - How to handle ArrayString? It's Copy & uninitialized (always an array of u8)

### CODE REVIEW

**Comment by bluss** [comment]
cc @arielb1 and thanks a lot for the help in searching for the best expression of this in Rust

**Comment by tbu-** [comment]
Is the `repr(C)` supposed to inhibit the enum optimization?

**Comment by bluss** [comment]
`repr(C)` was put there only there so that we can cast the `*const MaybeUninit<T>` to `*const T`.  There is a missing link right now, that needs to be rationalized as sound for the intermediate `ManuallyDrop` too.

**Comment by bluss** [comment]
A question I didn't fully understand if it was answered:

If we have a `MaybeUninit<[T; 3]>` which is partially initialized; only its first element is initialized.

1. Is it sound to extract a `&[T; 3]` from this?
2. Must arrayvec instead extract a `*const T`?
  * With the eventual goal of course, of creating `&T` to an element only if that element is initialized.

**Comment by bluss** [comment]
Yesterday's discussion https://botbot.me/mozilla/rust-libs/2017-10-20/?msg=92551510&page=1

**Comment by tbu-** [comment]
Thanks for the link to the discussion. Sounds like having a `&[T; 3]` with uninitialized elements is UB or at least not clearly not UB. We could work with `*mut [T; 3]` and `*mut [T]`.

**Comment by bluss** [comment]
What we were trying to do is to get docs amended for ManuallyDrop so that it can be MaybeUnitialized, but that seems to not be such a good idea. I'm still not entirely convinced.

**Comment by bluss** [comment]
New version in #97

**Pull request closed without merging**
