### PR TITLE
Support no_std in nodrop

### PR DESCRIPTION
**Pull request by gereeter**
See #20.

### CODE REVIEW

**Comment by gereeter** [comment]
Ah - you are testing against Rust 1.2, which doesn't have stable `core`. Should I put this behind a cargo feature?

**Comment by bluss** [comment]
Right, we need a solution for that. Nice crate that doesn't need anything from std.

I want to use a `std` feature and have it enabled by default. There was some discussion about what the community's standard solution for this was going to be, but I think that's fine.

Moving the baseline from Rust 1.2 is fine, but not all the way up to Rust 1.6 yet I think?

Discussion in https://github.com/rust-lang-nursery/libc/pull/146

**Comment by bluss** [comment]
Heck, I think Rust 1.6 is fine, we can do a bump to version 0.2. This crate doesn't take any harm from 0.1 -> 0.2 bumping does it, it doesn't share types really with other crates, so the implications should be minimal.

**Comment by bluss** [comment]
To edit that thought, that makes it complicated for ArrayVec.. where a major version bump has larger ramifications..

**Comment by bluss** [comment]
Thanks. I'll merge this & fix it up.

**Pull request merged**
