### PR TITLE
Optionally implement Zeroize on ArrayVec/ArrayString

### PR DESCRIPTION
**Pull request by elichai**
This will be very useful as `ArrayVec` is used in cryptographic libraries so the user might want to zero out the content (See https://github.com/BLAKE3-team/BLAKE3/pull/309)

P.S. I'm not sure about the use of `unsafe` in the test examples, I can split them into unit tests if wanted.

### CODE REVIEW

**Comment by bluss** [comment]
looks good to me, can you add the new feature somewhere in the github actions test matrix?

**Comment by elichai** [comment]
> looks good to me, can you add the new feature somewhere in the github actions test matrix? In an existing case is fine.

Done :) I used that opportunity to add benches to one of the matrix entries and to enable all features on the `miri` run

**Comment by elichai** [comment]
Sorry, I used the wrong yaml syntax, fixed and tested locally (with `act`)

**Comment by bluss** [comment]
thanks

**Pull request merged**
