### PR TITLE
Implement TryFrom<Slice> for ArrayVec

### LINKED ISSUE #106: ArrayVec from slice
How can i create an ArrayVec from a slice?
There is no ArrayVec::from(&[T])

### PR DESCRIPTION
**Pull request by paulkernfeld**
fixes #106

### CODE REVIEW

**Comment by paulkernfeld** [comment]
I implemented this using `try_extend_from_slice` so it requires that `A::Item: Copy`. It would also be possible to do this so that `A::Item` only needs to be `Clone`, not `Copy`.

**Comment by bluss** [comment]
Please write it as fixes #106   - https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword


We can implement it with .extend instead, and then it can support Clone. It can be an efficiency trade-off (depending on optimization), but I think aiming for the Clone version is good.

**Comment by paulkernfeld** [comment]
Sure, no problem! I redid it to support `Clone`.

**Comment by bluss** [comment]
Thanks! Feel free to ping me, I will inevitably forget to publish a new version

**Pull request merged**
