### PR TITLE
Add `Default` implementation for `ArrayString`

### LINKED ISSUE #67: Should `ArrayString` implement `Default`?
I don't know that it should, but `ArrayVec` does, and `String` does. I just noticed that `ArrayString` does not, and while it isn't blocking for me (in fact it reminded me that I should remove the `: Default` requirements on some of my impls) I thought I should point it out!

### PR DESCRIPTION
**Pull request by tbu-**
Fixes #67.

### CODE REVIEW

**Comment by tbu-** [comment]
@bluss Can I merge small changes like this myself, or would you rather review them?

**Comment by bluss** [comment]
Let's start out by reviewing everything I think. Maybe I'm a bad sport, because I just pushed three doc changes just before I saw this, sorry about that. Nothing is really critical until we make releases anyway. I'll approve this and you can merge though..

**Comment by bluss** [comment]
I can release 0.4.1 with this and the doc fixes. Anything else we want to get in?

**Comment by tbu-** [comment]
Should be good.

We want #66 at some point, but I don't have an implementation yet.

**Comment by bluss** [comment]
Great, yes those should be simple to add.

**Pull request merged**
