### PR TITLE
Fix bounds checking in ArrayVec::insert(index, element)

### LINKED ISSUE #38: `insert` does no bounds checking
The function looks wrong for cases `self.len() < index < self.capacity()`.

### PR DESCRIPTION
**Pull request by bluss**
Must be `index <= len && index < capacity`

Fixes #38

### CODE REVIEW

**Comment by bluss** [comment]
Oh, there's more broken than that. Let's fix overwriting too.

**Comment by tbu-** [comment]
I think panicking would be more appropiate, according to the documentation and my gut feeling. No element is pushed out if we're passing an out-of-range index.

Otherwise the documentation should probably be updated to reflect that the inserted element is returned for out-of-bounds inserts.

**Comment by bluss** [comment]
You have a good point.

**Comment by bluss** [comment]
I'm not comfortable with doing that, it will simply be something to consider for the next major version. This version has the weird shift out behavior already (and the tests ensure it).

**Comment by bluss** [comment]
Current tests try things like:

```
     let mut v = ArrayVec::from([2]);
     assert_eq!(v.insert(1, 1), Some(1));
     assert_eq!(v.insert(2, 1), Some(1));
```

**Comment by tbu-** [comment]
Right.

**Pull request merged**
