### PR TITLE
Follow simplification of Vec::retain() (rust-lang/rust#91527)

### PR DESCRIPTION
**Pull request by niklasf**
Follows rust-lang/rust#91527. This is neutral in my go-to benchmarks, but it's probably good to keep the implementation in sync regardless.

Edit: Looks like miri does not like this, whereas it doesn't mind std. Reminds me of https://github.com/bluss/arrayvec/pull/174#pullrequestreview-594795729. Will debug later.

### CODE REVIEW

**Comment by niklasf** [comment]
Fixed by dereferencing the pointer only for `f(unsafe { &mut *cur })`. To be honest, I don't understand how std gets away with not doing it like that.

**Comment by AngelicosPhosphoros** [comment]
@bluss Can we merge that?
It would fix complains of miri about retain.
https://github.com/bluss/arrayvec/issues/221

**Comment by AngelicosPhosphoros** [comment]
@niklasf 
At this moment miri also don't like `ArrayVec::drain` and `ArrayVec::retain`.

**Comment by niklasf** [comment]
Looks like the stacked borrow violations have been addressed in a different way.

**Pull request closed without merging**
